### ISSUE TITLE
Burp v1.7.35, reCAPTCHA v0.7 Get image失败

### ISSUE THREAD

**Issue by cbwang2016** [bit4woo/reCAPTCHA#2]
v0.6也失败，v0.5成功。
![image](https://user-images.githubusercontent.com/18070081/42861325-194b120a-8a8d-11e8-9777-82db12c449c6.png)
图片是v0.7的错误信息。v0.6不会显示错误信息

**Comment by bit4woo** [comment]
麻烦提供URL给我，以便调试，谢谢

**Comment by cbwang2016** [comment]
http://query.bjeea.cn/queryService/rest/admission/110

**Comment by bit4woo** [comment]
![image](https://user-images.githubusercontent.com/8793481/43765430-80f49e00-9a62-11e8-9138-aa507a2c25a5.png)
没毛病啊

**Comment by cbwang2016** [comment]
您是什么操作系统？Java版本？Oracle还是openjdk？

**Comment by cbwang2016** [comment]
```
>java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
Windows 10
没用代理。再次尝试v0.7仍然不行:
```
java.lang.NullPointerException: Response cannot be null
```

难道是burp版本v1.7.35的问题？或者是keygen的问题？
我用的是在https://github.com/jas502n/BurpSuite_Pro_v1.7.32 下载的，hash校验和官网一致。

**Comment by wo1fb0ss** [comment]
我也出现了一样的问题
版本一样
在Mac上运行

**Comment by UnifyUs** [comment]
java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
win10   burp v1.7.37,  reCAPTCHA 0.8 也出现这样的错误

**Comment by bit4woo** [comment]
请求图片的函数使用了burp提供的方法，如果请求失败请检查网络状态和burp相关设置，该问题无法彻底解决，现关闭该issue。
