### ISSUE TITLE
验证码不刷新,一直在用第一次获取的跑

### ISSUE THREAD

**Issue by sdfjksd** [bit4woo/reCAPTCHA#3]
![image](https://user-images.githubusercontent.com/43327091/45669936-1217d980-bb54-11e8-9028-8f9fba6c9e3d.png)
求解,如何破

**Comment by sdfjksd** [comment]
![image](https://user-images.githubusercontent.com/43327091/45670190-b26dfe00-bb54-11e8-9389-288c21fc0083.png)
第一个验证码也通不过验证,码是对的,但是提示如图

**Comment by duyannnnn** [comment]
同样，验证码不刷新

**Comment by bit4woo** [comment]
请查看burp同步目录下，下载的图片是否有增多，如方便请提供遇到问题的URL

**Comment by bit4woo** [comment]
请试用最新版：https://github.com/bit4woo/reCAPTCHA/releases/tag/v1.0
