### ISSUE TITLE
burp1.7.37使用插件直接卡死

### ISSUE THREAD

**Issue by wooyunvip** [bit4woo/reCAPTCHA#4]
burp1.7.37点击获取image后burp就卡死掉了
![image](https://user-images.githubusercontent.com/24996837/47338568-07a8ac80-d6cb-11e8-8f12-b1340f23ed0f.png)

**Comment by bit4woo** [comment]
请查看extender下是否有报错，另外如有下载成功的图片文件（burp所在目录），使用notepad++打卡查看信息

**Comment by bit4woo** [comment]
问题已修复
