### ISSUE TITLE
匹配不到正确的验证码

### ISSUE THREAD

**Issue by akens1213** [bit4woo/reCAPTCHA#5]
burp1.7.34 用V0.8抓不到验证码，用V0,7就没问题。但是在暴力破解的时候总是匹配不到正确的验证码，提示验证码错误。

**Comment by anonymity3712** [comment]
> burp1.7.34用V0.8抓不到验证码，用V0,7就没问题。但是在暴力破解的时候总是匹配不到正确的验证码，提示验证码错误。

我也是这样的 请问你找到解决办法了么

**Comment by bit4woo** [comment]
请试用最新版：https://github.com/bit4woo/reCAPTCHA/releases/tag/v1.0
