### ISSUE TITLE
失败了 java.lang.NullPointerException: Response cannot be null

### ISSUE THREAD

**Issue by Eisx11o** [bit4woo/reCAPTCHA#7]
http://47.110.86.5:9999
GET /index.php?g=api&m=checkcode&a=index&length=4&font_size=22&width=248&height=42&use_noise=1&use_curve=0&refresh=0.6600757433620807&refresh=0.21375486171371927&refresh=0.4042291609691442 HTTP/1.1
Host: 47.110.86.5:9999
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
DNT: 1
Accept: image/webp,image/apng,image/*,*/*;q=0.8
X-Forwarded-For: 36.5.192.76
Client-IP: 36.5.192.76
Referer: http://47.110.86.5:9999/index.php?g=admin&m=public&a=login
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Cookie: PHPSESSID=au83hdof17fc29g08n7mre14j6
Connection: close
X-Forwarded-For:208.117.216.68

**Comment by bit4woo** [comment]
参见 #2
